notifications:
  email: false

sudo: true

os:
- linux

language: node_js

node_js:
- 8.9.1

env:
  global:
    secure: "E4wwUwiR+uB657k2EnKirzB49izhr8MY8gAnCaiqzfmop1UpEWT2SnxM/IzLQCUdKmRK8g5bz30EjF8R2sHDfL5ok35KSGEHq0FEv6a2vzb8hj+6se1KjV1WRy0qof7pdAWALtltY4KItXwNvFx30cFUcnueoL1QZFEBeywp3gKx3DzqFZAbRaXicBcBPKd3FF5yT/3TIXdsm6v/Tfa8npmWAKviS3GhgV3LEj84KYRviVPhqd7JsvgMxKCDfaXVSzymxW2ObIo/KqL9k28xaAeL050VwPXynUvVFlCuScPOSGuJfegGCfRPLt6/wXgkA3/U9A6EyE4VbxLmwDpXmr7/1ZahmtVw6GszWqlkG0dwTeXizpdnb5zkuezuA4iJf0ZI6AU+8bO2xlIVb6bU+N58cRG0ncrlOE8kvpsNXwleHKEz/DWS5kMvuPZCB+I5/sVdsKAM8Q+6erbHlSATxTZNN/M7c2QOtcCkp3T0GKviS43h+41gXBVsgdYojQ7Cyhp8t7U1GjcXDhaTipp6MZq+jGtbPWay33rwh7chAoltpF3yqu1F3hfbYqFObm/+juipxexB5QtT8SN8f08Hfk/0Af+ycc6LNfaEvawslPg2EJOyPwl45yfvqiq1XB8LcrMsfIldtwKIU9KBOZ0rxjyQo2m7HW9o+NLekrKJXqo="

addons:
  apt:
    packages:
      - libsecret-1-dev

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi

install:
- npm install -g gulp;
- npm install;

script:
- git ls-tree -r HEAD --name-only | grep ".*.[t|j]s$" | xargs ./node_modules/prettier/bin/prettier.js --write --print-width 100 --single-quote --trailing-comma es5
- if [[ $(git diff-index HEAD --) ]]; then
    ./node_modules/prettier/bin/prettier.js -v;
    git diff;
    echo "Prettier Failed. Run `gulp` or `gulp forceprettier`";
    exit 1;
  else
    echo "Prettier passed.";
  fi
- gulp
- npm test --silent;

before_deploy:
- npm install -g vsce;
- vsce package;

deploy:
- provider: releases
  api_key:
    secure: PmBcza43E3Y5/OxmR2V3nLJSBW9LildJCHdNQrKC0AndO6b14K+FLq3lwUBNX36q08noRX1V/nrYiDIFbZf8AQNq7j+rsR6mJOTXmu/pThrz0ugBK12f5aVoJOAdPPD2XZ/Cu7nLNvqVbLgZIqACVwWzCukSD0/3JWFv1w3yjGj/t1QNBHJoT7Wy1K6a1d3IISnDC9XROBYWvG/4IZipTAiv8yD0TMncgVaWxjEng5lhtmDE+XhBQU7Z5Ywc9IJMgajos+Ix6j+bju7Evta26+tLvonwC3dK8eeUZbIqdanrGl1zW0yft15y2SYo1YYQE6qLFO1kDsR90iY1YaW94vGyDJ3TLDAEjyZ3RMYv1OFOKOc6fhV3l5piyacCmvc30gP+AKjlukxgckYRY1soDNW5xqjcMSluaOMumNPbXpVsx7Kup+ceYkktQBSoTHtZFxt1uQmo7KY9IcNIsZuRP2hLcxV0eI6HI78THa56vTffxXWBZ2NYkKJ6gBADghQlJaz6D40yX2Qj2XsXH09aaY6oQ2Y/x3TZTLxwbyiHA2DPVY5e06GDRaEeavIyDiM9p4wlgsYuS4vDXGbNkzoBZuijpKw3fG1tf39+rUqlVw2LBN1kroAiNfHjaalTwsWS3F9y1ispCALYUuMl4lIAsgGXYgOZbfPO5sof6Wjvg4Q=
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: VSCodeVim/Vim
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  script: vsce publish -p $VS_TOKEN
  skip_cleanup: true
  on:
    repo: VSCodeVim/Vim
    tags: true
    condition: $TRAVIS_OS_NAME = linux
