notifications:
  email: false

sudo: true

os:
- linux

language: node_js

node_js:
- 8.9.1

env:
  global:
    secure: "TBppwshoN5d6uhzTEgcx9KB01z9jUVG3TjlbNioTo7IygfJsjWHdTwQlt/mpfXMjwo5lQ9h0eLghKUtEhpJqiyH8Mtg7ZkYJiR0ZV1UTrmM1qZJLo2rhrO+7twWilZ84TUBFMYXcgTimXkwLwA9Jh56KHi4P32NNUneImYDnL18yNj6oSul7r4Z951o1ikbgt7lirXgybe7NmixkATE7j1Obf9DW+9s287Z/LVE3a9O7tQLvow+m3NuktWGbr+pQu4siMbD96WpA8tvYvJEHnS0g66d3u7FqzAabR4E1eZbzjKDx8SbZ45rfdFuhy6YyV0xNFa2jm/N8MKjttNezLZCvLEveHKaNl522zwx/niMDlkpvnNlFLmwuyqnw429NRT/SEWhuOdQOQdzOju1hUWAF/lIodAyhqeF9yGX8H+2QHHxaS7tgDllVslz03695sqXye5OAHJifkzfNX5Grr6K3cEPSD955ijGC0FB5ejB+pBK+KUzd1tlzys/1Q6KPwN9oRyoeude7fDDkvH2jY9ZyrfImqUBKUlGFFIa7gEBAl0JhJc+tGtvYySHMhs2KC5PSCf9OrPvaI02bJvhi4Xnjfk9OGn3bmVOCwUcGZieJMxU8chBxf+YQITv5b0SBjKPZZd2QuNUYlxKlFZbGvbjvOSQUcRumFKwCgbfV79E="


before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi

install:
- npm install -g gulp;
- npm install;
- sudo apt-get install libsecret-1-dev

script:
- git ls-tree -r HEAD --name-only | grep ".*.[t|j]s$" | xargs ./node_modules/prettier/bin/prettier.js --write --print-width 100 --single-quote --trailing-comma es5
- if [[ $(git diff-index HEAD --) ]]; then { ./node_modules/prettier/bin/prettier.js -v; git diff; echo "Prettier Failed. Run `gulp` or `gulp forceprettier`"; exit 1; }; else echo "Prettier passed."; fi
- gulp
- npm test --silent;

before_deploy:
- npm install -g vsce;
- vsce package;

deploy:
- provider: releases
  api_key:
    secure: PmBcza43E3Y5/OxmR2V3nLJSBW9LildJCHdNQrKC0AndO6b14K+FLq3lwUBNX36q08noRX1V/nrYiDIFbZf8AQNq7j+rsR6mJOTXmu/pThrz0ugBK12f5aVoJOAdPPD2XZ/Cu7nLNvqVbLgZIqACVwWzCukSD0/3JWFv1w3yjGj/t1QNBHJoT7Wy1K6a1d3IISnDC9XROBYWvG/4IZipTAiv8yD0TMncgVaWxjEng5lhtmDE+XhBQU7Z5Ywc9IJMgajos+Ix6j+bju7Evta26+tLvonwC3dK8eeUZbIqdanrGl1zW0yft15y2SYo1YYQE6qLFO1kDsR90iY1YaW94vGyDJ3TLDAEjyZ3RMYv1OFOKOc6fhV3l5piyacCmvc30gP+AKjlukxgckYRY1soDNW5xqjcMSluaOMumNPbXpVsx7Kup+ceYkktQBSoTHtZFxt1uQmo7KY9IcNIsZuRP2hLcxV0eI6HI78THa56vTffxXWBZ2NYkKJ6gBADghQlJaz6D40yX2Qj2XsXH09aaY6oQ2Y/x3TZTLxwbyiHA2DPVY5e06GDRaEeavIyDiM9p4wlgsYuS4vDXGbNkzoBZuijpKw3fG1tf39+rUqlVw2LBN1kroAiNfHjaalTwsWS3F9y1ispCALYUuMl4lIAsgGXYgOZbfPO5sof6Wjvg4Q=
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: VSCodeVim/Vim
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  script: vsce publish -p $VS_TOKEN
  skip_cleanup: true
  on:
    repo: VSCodeVim/Vim
    tags: true
    condition: $TRAVIS_OS_NAME = linux
